'use client';
import {useEffect,useRef,useState} from 'react';import {mapTraits} from '@/domain/keywords';import {generateLocalPartDraft} from '@/server/providers/local';import {findPart,PARTS} from '@/domain/catalog';import type {ModelTask,PartDraft} from '@/server/providers/types';import type {CreatureDrafts,CreatureInputs,CreatureSlot} from '@/server/providers/creature';import styles from './ForgePanel.module.css';import detail from './CreatureForge.module.css';
const slots:CreatureSlot[]=['head','body','legs'];const labels:Record<CreatureSlot,string>={head:'头部 · 攻击',body:'身体 · 守护',legs:'脚部 · 机动'};const oldKey='shellforge.creature-forge.v1';const key='shellforge.creature-forge.v2';
const DEMOS=[{name:'熔岩巨蟹',lore:'火山熄灭以前，它已把第一枚火种藏进壳里。',text:'会喷火、披着岩壳、用弹簧腿跳跃的熔岩巨蟹',ids:['h01','b01','l03'] as [string,string,string],parts:{head:'火焰钳嘴',body:'熔岩岩壳',legs:'弹簧跳跃'}},{name:'棉花糖兔',lore:'看起来轻软的家伙，能在守卫眨眼前绕到身后。',text:'棉花糖一样软、能快速奔跑和再生的兔子',ids:['h02','b03','l01'] as [string,string,string],parts:{head:'糖霜面罩',body:'棉花软壳',legs:'疾跑兔子'}},{name:'镜潮钻龟',lore:'它记得每一次撞击，也记得如何把力量送还。',text:'会穿刺、披着镜面坚甲、吸附岩壁的海龟',ids:['h03','b01','l02'] as [string,string,string],parts:{head:'穿刺钻角',body:'镜面岩甲',legs:'吸附岩足'}}];
const ideas=['会在月光下发热的熔岩巨蟹','像棉花糖一样软但跑得飞快的兔子','背着珊瑚钟楼的深海鲸','长着玻璃眼睛的雷电乌龟','由旧船锚组成的贪吃海怪','能把泡泡变成盾牌的小龙','披着苔藓的沉睡石像','住在贝壳里的影子狐狸','会反弹攻击的铜镜螃蟹','腿像弹簧的火山蜥蜴','一只爱唱歌的水晶章鱼','背负小岛的慢吞吞巨兽','会隐身的月牙水母','穿着锈盔甲的深海骑士','能吐出蓝色火焰的海马','由海草和齿轮拼成的鹿','头上长着珊瑚树的甲虫','踩着浪花滑行的银鱼','脾气骄傲的珍珠狮子','会吞掉光线的黑曜石鸟','长满蘑菇的岩石犀牛','软绵绵却力大无穷的海豹','能蓄积雷电的贝壳龟','带着回旋刀片的螳螂虾','躲在雾里的长腿猫','穿刺坚甲的铁嘴鹭','用尾巴守护同伴的海龙','爱打盹的再生珊瑚兽','一碰就燃烧的海底花朵','会模仿守卫动作的镜面猴'];
type Jobs=Partial<Record<CreatureSlot,ModelTask>>;interface Session{inputs:CreatureInputs;drafts:CreatureDrafts|null;jobs:Jobs}
interface Project extends Session{id:string;createdAt:number}
interface Projects{activeId:string;items:Project[]}
const initial=(ids:[string,string,string]):Session=>({inputs:{description:'一只会喷火、披着岩壳、用弹簧腿跳跃的熔岩巨蟹',head:{partId:ids[0],prompt:'一只会喷火、披着岩壳、用弹簧腿跳跃的熔岩巨蟹'},body:{partId:ids[1],prompt:'一只会喷火、披着岩壳、用弹簧腿跳跃的熔岩巨蟹'},legs:{partId:ids[2],prompt:'一只会喷火、披着岩壳、用弹簧腿跳跃的熔岩巨蟹'}},drafts:null,jobs:{}});
function migrateSession(raw:Session):Session { if(!raw.drafts)return raw;const d=raw.drafts as CreatureDrafts;const complete=typeof d.name==='string'&&typeof d.lore==='string'&&slots.every(slot=>Array.isArray(d[slot]?.keywords)&&Array.isArray(d[slot]?.reasons));if(complete)return raw;const next={...d,name:typeof d.name==='string'?d.name:'旧造物',lore:typeof d.lore==='string'?d.lore:'来自旧版本的造物设定。'} as CreatureDrafts;for(const slot of slots){const old=d[slot] as PartDraft,trait=mapTraits(raw.inputs[slot].prompt,slot);next[slot]={...old,keywords:trait.keywords,cost:trait.cost,reasons:trait.reasons}}return {...raw,drafts:next};}
const validJob=(x:unknown):x is ModelTask=>Boolean(x&&typeof x==='object'&&/^[a-f0-9-]{36}$/.test((x as ModelTask).id)&&/^[hbl]0[1-3]$/.test((x as ModelTask).partId));
const freshProject=(ids:[string,string,string]):Project=>({...initial(ids),id:crypto.randomUUID(),createdAt:Date.now()});
interface Props{partIds:[string,string,string];availablePartIds:string[];retiredPartIds?:string[];disabled:boolean;tripoConfigured:boolean;deepseekConfigured:boolean;demoMode:boolean;onProjectDrafts:(projectId:string,drafts:CreatureDrafts)=>void;onPartTask:(projectId:string,slot:CreatureSlot,task:ModelTask,draft:PartDraft)=>void;onApplyProject:(projectId:string,drafts:CreatureDrafts,jobs:Jobs)=>void}
export default function CreatureForge({partIds,availablePartIds,retiredPartIds=[],disabled,tripoConfigured,deepseekConfigured,demoMode,onProjectDrafts,onPartTask,onApplyProject}:Props){
 const [projects,setProjects]=useState<Projects>(()=>{const p=freshProject(partIds);return {activeId:p.id,items:[p]}});const ref=useRef(projects);const hydrated=useRef(new Set<string>());const session=projects.items.find(p=>p.id===projects.activeId)||projects.items[0];const [advanced,setAdvanced]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('写一句话造物，关键词将决定战斗能力。3D 锻造会在后台继续。');const [presetIndex,setPresetIndex]=useState(0);const sessionKey=demoMode?key+'.demo':key;const inflight=useRef(new Set<string>());
 const saveProjects=(next:Projects)=>{ref.current=next;setProjects(next);try{localStorage.setItem(sessionKey,JSON.stringify(next))}catch{setMessage('本机无法保存锻造记录。')}};
 const changeProject=(id:string,change:(p:Project)=>Project)=>{const current=ref.current;if(!current.items.some(p=>p.id===id))return;saveProjects({...current,items:current.items.map(p=>p.id===id?change(p):p)});};
 const save=(s:Session)=>changeProject(ref.current.activeId,p=>({...p,...s}));
 useEffect(()=>{try{const stored=JSON.parse(localStorage.getItem(sessionKey)||'null') as Projects|null;const old=JSON.parse(localStorage.getItem(demoMode?oldKey+'.demo':oldKey)||'null') as Session|null;let restored:Projects|null=null;if(stored&&Array.isArray(stored.items)&&stored.items.length&&stored.items.every(p=>p&&typeof p.id==='string'&&p.inputs&&p.jobs&&slots.every(s=>typeof p.inputs[s]?.prompt==='string'&&/^[hbl]0[1-3]$/.test(p.inputs[s].partId)&&(!p.jobs[s]||validJob(p.jobs[s]))))){restored={activeId:stored.items.some(p=>p.id===stored.activeId)?stored.activeId:stored.items[0].id,items:stored.items.map(p=>({...p,...migrateSession(p)}))};}else if(old?.inputs&&old.jobs&&slots.every(s=>typeof old.inputs[s]?.prompt==='string'&&(!old.jobs[s]||validJob(old.jobs[s])))){const p={...migrateSession(old),id:crypto.randomUUID(),createdAt:Date.now()};restored={activeId:p.id,items:[p]};}if(restored)saveProjects(restored);}catch{setMessage('旧锻造记录无法读取；存档与已有模型文件没有被删除。')}},[sessionKey]);
 useEffect(()=>{if(disabled)return;for(const p of projects.items){if(!p.drafts||hydrated.current.has(p.id))continue;hydrated.current.add(p.id);if(slots.some(s=>retiredPartIds.includes(p.id+':'+s)))continue;onProjectDrafts(p.id,p.drafts);for(const s of slots)if(p.jobs[s])onPartTask(p.id,s,p.jobs[s]!,p.drafts[s]);}},[disabled,projects.items,retiredPartIds]);
 const edit=(slot:CreatureSlot,value:string)=>{const input={...session.inputs,description:undefined,[slot]:{...session.inputs[slot],prompt:value.slice(0,120)}};save({...session,inputs:input,drafts:null,jobs:{}})};
 const editAll=(value:string)=>{const input={...session.inputs,description:value.slice(0,240)};for(const slot of slots)input[slot]={...input[slot],prompt:value.slice(0,120)};save({...session,inputs:input,drafts:null,jobs:{}})};
 const selectBlueprint=(slot:CreatureSlot,id:string)=>{if(!availablePartIds.includes(id)||findPart(id).slot!==slot)return;save({...session,inputs:{...session.inputs,[slot]:{...session.inputs[slot],partId:id}},drafts:null,jobs:{}})};
 async function submit(projectId:string,slot:CreatureSlot,draft:PartDraft,retry=false){const id=crypto.randomUUID();const pending:ModelTask={id,partId:draft.partId,prompt:draft.visualPrompt,startedAt:Date.now(),status:'submitting',progress:0,modelPath:null,updatedAt:Date.now(),nextPollAt:Date.now()+5000,message:'贝壳已经合拢，正在提交…'};changeProject(projectId,p=>({...p,jobs:{...p.jobs,[slot]:pending}}));onPartTask(projectId,slot,pending,draft);
  try{const r=await fetch('/api/generation/model',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,partId:draft.partId,prompt:draft.visualPrompt+'; single object, centered, front view facing camera, flat bottom, no base, no background; stylized, cartoon, hand-painted texture, soft colors, cute proportions, low detail',retry}),signal:AbortSignal.timeout(40000)});const b=await r.json();if(!r.ok||!b.task)throw Error(b.error||'任务提交失败');const task=b.task as ModelTask;changeProject(projectId,p=>p.jobs[slot]?.id===id?{...p,jobs:{...p.jobs,[slot]:task}}:p);onPartTask(projectId,slot,task,draft);return task;
  }catch(e){const unknown={...pending,status:'unknown' as const,message:'提交结果不明：'+(e instanceof Error?e.message:'网络中断')+'。请查询原任务，不会自动重复付费提交。'};changeProject(projectId,p=>p.jobs[slot]?.id===id?{...p,jobs:{...p.jobs,[slot]:unknown}}:p);onPartTask(projectId,slot,unknown,draft);return unknown;}}
 async function design(){if(busy)return;const projectId=session.id;if(demoMode){const preset=DEMOS[presetIndex];const drafts={} as CreatureDrafts;for(let i=0;i<slots.length;i++){const slot=slots[i],id=preset.ids[i],part=generateLocalPartDraft(preset.parts[slot],id),trait=mapTraits(preset.parts[slot],slot);drafts[slot]={...part,keywords:trait.keywords,cost:trait.cost,reasons:trait.reasons}}drafts.name=preset.name;drafts.lore=preset.lore;changeProject(projectId,p=>({...p,drafts,jobs:{}}));hydrated.current.add(projectId);onProjectDrafts(projectId,drafts);setMessage('离线演示：本地规则与内置 GLB，不请求 API。');return}setBusy(true);setMessage(deepseekConfigured?'正在把描述变成三件能力卡，随后并行提交模型…':'本地读取描述里的特征并生成能力卡…');try{
  const inputs=session.inputs;const parts=Object.fromEntries(slots.map(s=>[s,inputs[s]]));const selectedPartIds=slots.map(s=>inputs[s].partId) as [string,string,string];const payload=inputs.description?{description:inputs.description,partIds:selectedPartIds}: {parts};
  const r=await fetch('/api/generation/creature',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:AbortSignal.timeout(40000)});const b=await r.json();if(!r.ok)throw Error(b.error||'造物设计失败');const drafts=b.drafts as CreatureDrafts;changeProject(projectId,p=>({...p,drafts,jobs:{}}));onProjectDrafts(projectId,drafts);setMessage(b.warning||'能力卡已完成；三个模型任务正在后台独立提交。可以立即新建下一只造物。');
  hydrated.current.add(projectId);if(tripoConfigured){for(const s of slots)void submit(projectId,s,drafts[s]);}else setMessage((b.warning?b.warning+' ':'')+'没有 Tripo 配置，内置外观也能直接出征。');
 }catch(e){setMessage(e instanceof Error?e.message:'设计失败，本地预置蓝图仍可游玩。')}finally{setBusy(false)}}
 async function query(projectId:string,slot:CreatureSlot,job:ModelTask){if(inflight.current.has(job.id))return;inflight.current.add(job.id);try{const r=await fetch('/api/generation/model/'+job.id,{cache:'no-store'});const b=await r.json();if(!r.ok)throw Error();const p=ref.current.items.find(x=>x.id===projectId);if(p?.jobs[slot]?.id===job.id){changeProject(projectId,current=>({...current,jobs:{...current.jobs,[slot]:b.task}}));if(p.drafts)onPartTask(projectId,slot,b.task,p.drafts[slot]);}}catch{setMessage(labels[slot]+'查询暂时失败，任务编号已保留。')}finally{inflight.current.delete(job.id)}}
 useEffect(()=>{const timer=setInterval(()=>{for(const p of ref.current.items)for(const slot of slots){const job=p.jobs[slot];if(job&&['queued','processing','deferred','submitting'].includes(job.status)&&Date.now()>=job.nextPollAt)void query(p.id,slot,job)}},1800);return()=>clearInterval(timer)},[]);
 const ready=slots.every(s=>session.jobs[s]?.status==='succeeded'&&session.jobs[s]?.modelPath);const retired=slots.some(s=>retiredPartIds.includes(session.id+':'+s));
 const apply=()=>{if(!session.drafts)return;onApplyProject(session.id,session.drafts,session.jobs);setMessage('造物已装配；未完成的模型会在后台继续孵化。')};
 const draft= session.drafts;
 return <div className={styles.forge}><div className={styles.heading}><span>THE FORGE / 造物远征</span><h2>用一句话唤醒你的造物</h2><p>每只造物有独立的头、身、脚任务。提交后可以继续创造下一只，旧任务会保留并继续查询。</p></div>
 <div className={detail.projectBar}><strong>造物队列 · {projects.items.length}</strong><button type="button" disabled={disabled||projects.items.length>=30} onClick={()=>{const p=freshProject(partIds);saveProjects({activeId:p.id,items:[p,...ref.current.items]});setMessage('新造物已就绪；之前的模型任务继续在后台运行。')}}>＋ 新建造物</button></div>
 <div className={detail.projectList} aria-label="造物任务队列">{projects.items.map(p=><button type="button" key={p.id} aria-pressed={p.id===session.id} onClick={()=>saveProjects({...ref.current,activeId:p.id})}><strong>{p.drafts?.name||p.inputs.description?.slice(0,12)||'未命名造物'}</strong><small>{slots.map(s=>{const j=p.jobs[s];return labels[s].split(' · ')[0]+':'+(j?.status==='succeeded'?'完成':j?.status==='deferred'?'排队重试':j?.status==='unknown'?'需核查':j?.status==='failed'?'失败':j?'生成中':p.drafts?'待生成':'未设计')}).join(' / ')}</small></button>)}</div>
 <div className={detail.blueprintPicker} aria-label="造物蓝图选择">{slots.map((slot,index)=>{const slotParts=PARTS.filter(p=>p.slot===slot&&availablePartIds.includes(p.id));return <label key={slot}><span>{labels[slot].split(' · ')[0]}蓝图</span><select aria-label={labels[slot].split(' · ')[0]+'蓝图'} value={session.inputs[slot].partId} disabled={disabled||busy||Boolean(draft)} onChange={e=>selectBlueprint(slot,e.target.value)}>{slotParts.map(part=><option key={part.id} value={part.id}>{part.name}</option>)}</select><small>{slotParts.find(p=>p.id===session.inputs[slot].partId)?.description||'选择已解锁部件'}</small></label>})}</div>
 {demoMode&&<div className={detail.demoPresets} aria-label="离线预置造物">{DEMOS.map((p,i)=><button type="button" key={p.name} aria-pressed={presetIndex===i} disabled={disabled||busy||Boolean(draft)} onClick={()=>{setPresetIndex(i);const input={...session.inputs,description:p.text};for(let n=0;n<slots.length;n++)input[slots[n]]={partId:p.ids[n],prompt:p.parts[slots[n]]};save({...session,inputs:input,drafts:null,jobs:{}})}}><strong>{p.name}</strong><small>本地素材 · 无 API</small></button>)}</div>}
 {!advanced?<label className={detail.singleInput}><strong>用一句话描述你的造物</strong><textarea maxLength={240} value={session.inputs.description||''} disabled={disabled||busy||Boolean(draft)} onChange={e=>editAll(e.target.value)}/><span>{(session.inputs.description||'').length}/240</span></label>:<div className={detail.creatureInputs}>{slots.map(slot=><label key={slot}><strong>{labels[slot]}</strong><small>蓝图：{findPart(session.inputs[slot].partId).name}</small><textarea maxLength={120} value={session.inputs[slot].prompt} disabled={disabled||busy||Boolean(draft)} onChange={e=>edit(slot,e.target.value)}/></label>)}</div>}
 <div className={styles.actions}>{!demoMode&&<button onClick={()=>{editAll(ideas[Math.floor(Math.random()*ideas.length)])}} disabled={disabled||busy||Boolean(draft)}>随机灵感</button>}{!demoMode&&<button onClick={()=>setAdvanced(v=>!v)} disabled={disabled||busy||Boolean(draft)}>{advanced?'改用一句话':'分别描述三件'}</button>}{!draft&&<button disabled={disabled||busy||(!session.inputs.description&&!slots.every(s=>session.inputs[s].prompt.trim()))} onClick={design}>{busy?'正在造物…':deepseekConfigured?'生成造物卡并锻造 3D':'本地生成造物卡并锻造'}</button>}{draft&&<button disabled={disabled||retired} onClick={apply}>{retired?'战败后已失去部件':ready?'装配并开始远征':'用临时外壳开始远征'} →</button>}</div>
 <p className={styles.message} role="status" aria-live="polite">{message}</p>{draft&&<><div className={detail.creatureHeader}><strong>{draft.name}</strong><p>{draft.lore}</p></div><div className={detail.creatureCards}>{slots.map(slot=>{const d=draft[slot],job=session.jobs[slot];return <article className={styles.draft} key={slot}><div><span>{labels[slot]} · {d.source==='deepseek'?'DEEPSEEK':'本地映射'}</span><strong>{d.name}</strong></div>{d.source==='local'&&d.fallbackReason&&<small>原因：{d.fallbackReason}</small>}<p>{d.description}</p><ul>{d.reasons.map((r,i)=><li key={i}>因为你写了「{r.quote}」→ 获得 <b>{r.keyword}</b>：{r.why}</li>)}</ul>{d.cost&&<small>代价 · {d.cost}</small>}<small>技能：{d.keywords.join('、')}</small>{job&&<div className={detail.creatureTask}><p>{job.status==='succeeded'?'已孵化 · 模型可用':job.status==='failed'?'孵化失败 · 保留临时外壳':job.status==='unknown'?'状态不明 · 未重复提交':job.status==='deferred'?'Tripo 限流 · 已排队自动重试':Date.now()-(job.startedAt||job.updatedAt)>120000?'锻造超过两分钟 · 仍在查询原任务':'贝壳正在闭合发光 · '+job.progress+'%'}</p><progress value={job.progress} max={100}/><small>{job.message}</small><small>任务编号：{job.id}</small>{['queued','processing','succeeded','unknown','deferred','submitting'].includes(job.status)&&<button disabled={busy} onClick={()=>void query(session.id,slot,job)}>查询原任务</button>}{job.status==='failed'&&<button disabled={busy||disabled} onClick={()=>void submit(session.id,slot,d,true)}>重新锻造</button>}{job.status==='unknown'&&<button disabled={busy||disabled} onClick={()=>{if(window.confirm('请先在 Tripo 控制台确认原任务没有继续运行或扣费。确认后才创建新任务，可能产生额外费用。继续？'))void submit(session.id,slot,d,true)}}>已核查，重试</button>}</div>}</article>})}</div></>}
 <p className={styles.foot}>技能按部位职责生效：头部攻击、身体守护、脚部机动。模型可在等待期间继续出征。</p></div>;
}
